services:

  Aws\S3\S3Client:
    arguments:
      - version: '2006-03-01'
        region: '%env(AMAZON_AWS_REGION)%'
        signature_version: 'v4'
        credentials:
          key: '%env(AMAZON_AWS_KEY)%'
          secret: '%env(AMAZON_AWS_SECRET_KEY)%'
  ekreative.amazon_s3:
    alias: Aws\S3\S3Client